raise Exception('error by you')
